on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Metrics
    steps:
      - name: Metrics embed
  
        # You may pin to the exact commit or the version.
        uses: lowlighter/metrics@v3.34
        with:
          template: repository
          user: living-with-machines
          repo: mapreader
